### ISSUE TITLE
Feature Request: Make Input and TextArea controlled components

### ISSUE THREAD

**Issue by JackSkylark** [technekes/cast-ui#148]
I don't currently see a way to provide values or listen for changes to either the Input or TextArea components. It would be great if we could have a `value` and `onChange` prop added to these components.

**Comment by dorokhovich-mikhail** [comment]
Well, Input's Props extends `React.InputHTMLAttributes<HTMLInputElement>` interface and Textarea's Props extends `React.TextareaHTMLAttributes<HTMLTextAreaElement>`

You know that values and all handlers already exists in these interfaces...

I had tested with passing values and different handler and it works. Could you clarify what the problem do you have?

**Comment by JackSkylark** [comment]
Perfect! I don't believe that these typings were in place a couple of days ago when I tested. Thank you for quickly responding.

**Comment by ben-dalton** [comment]
We currently have `HTMLAttributes` and `DOMAttributes` filtered out of the propTypes table to keep the table size down. Since this is the most common use of an input/textarea, we should at least add the `value` and `onChange` props to the example. @dorokhovich-mikhail, could you take that?

**Comment by ben-dalton** [comment]
Docs have been updated to include `value` and `onChange` as props.
