### ISSUE TITLE
  Border Radius on Select component selector visual issue

### ISSUE THREAD

**Issue by TrentCullinan9412** [technekes/cast-ui#230]
If I adjust the `borderRadius` on the `Select` component to say 40px, the menu border radius is also changed. For menu items that are hovered or selected, the radius is ignored and creates a visual issue. Would there be a way to separate those two properties? Otherwise make the hover and active be affected by the radius as well?

**Comment by bankai254** [comment]
@TrentCullinan9412 The effects `borderRadius` prop has been restricted to the `Select` control only and the menu will remain unaffected.

Expect the update on the next release
