### ISSUE TITLE
Collapsible Panel Issues

### ISSUE THREAD

**Issue by APmoss** [technekes/cast-ui#294]
A couple issues with collapsible panels. Here is my MVCE:

```
const PanelTest = () => {
    const [panelOpen, setPanelOpen] = React.useState(true)

    return (
        <Panel panelStyle={"primary"}>
            <PanelHeader
                panelStyle={"primary"}
                title="someTitle"
                toggleItem={() => setPanelOpen(!panelOpen)}
                isCollapsed={!panelOpen}
            />
            <Collapse isOpen={panelOpen}>
                <PanelBody panelStyle={"primary"}>
                    Lorem ipsum...
                </PanelBody>
            </Collapse>
        </Panel>
    )
}
```

1. There seems to be a typing issue with the `Collapse` component:
![collapseIssue](https://user-images.githubusercontent.com/2691950/58982597-6e7e6000-879a-11e9-9643-e4f4506744fc.PNG)
The MVCE works if typings are ignored.

2. I feel like the direction the chevron is facing is the opposite of what you would expect. For example, when isCollapsed is `true`, the chevron points up.
Theoretically, the values of `isCollapsed` and `isOpen` _should_ be the opposite, right?

**Comment by ben-dalton** [comment]
@APmoss I agree, the arrows seem to be reversed. We'll look into the typing issue. Thanks for raising it.

**Comment by ben-dalton** [comment]
@APmoss I checked with the design team and the default arrows are as intended. In anticipation of users wanting to change that behavior, we will add the ability to pass in `expandedIcon` and `collapsedIcon` props.

**Comment by dorokhovich-mikhail** [comment]
@APmoss isCollapsed and isOpen was added, also added expandedIcon and collapsedIcon
