### ISSUE TITLE
Panel Clipping

### ISSUE THREAD

**Issue by APmoss** [technekes/cast-ui#303]
Reopening #167.

Version: 0.4.4
Image:
![selectClipping](https://user-images.githubusercontent.com/2691950/59054222-ced3d700-8858-11e9-802f-d14d418cc1bf.PNG)

**Comment by ben-dalton** [comment]
@APmoss This may be the Select component needing a `menuPortalTarget` prop. The react-select issue is addressed [here](https://react-select.com/advanced#portaling).

**Comment by APmoss** [comment]
@ben-dalton I see, I've worked around it by adding `menuPortalTarget={document.body}`. Do you think this is a reasonable default that can be applied to all `Select` components? It would be helpful since this is a pretty common use case.

**Comment by APmoss** [comment]
Closing since we have found a solution. Thanks @ben-dalton!
